### ISSUE TITLE
About results on NewsRoom

### ISSUE THREAD

**Issue by xipq** [krystalan/chatgpt_as_nlg_evaluator#2]
Hi, thanks for your brilliant and comprehensive work.

I am recently working on using chatgpt to evaluate the NewsRoom benchmark since it is reported in this work. I found that there are three different annotations for each sample in the [Dataset](https://github.com/lil-lab/newsroom/tree/master/humaneval), which looks not very cosistent. 

Since you haven't released the newsroom data, I would like to know that, how you processed the NewsRoom dataset for correlation analysis (eg. averaging the 3 annotations, ultilizing all annotations, or else). Thanks and looking forward for your response.

**Comment by krystalan** [comment]
Hi, Sorry for the really late reply.

We average the three annotations, which is inspired by BARTScore. And you can find the corresponding files [here](https://github.com/neulab/BARTScore/tree/main/SUM/Newsroom)
